// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app_button': string;
  'app_buttons': string;
  'block_title': string;
  'image': string;
  'image_button': string;
  'menu': string;
  'overlay': string;
  'red': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
