// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue': string;
  'button': string;
  'buttonEnter': string;
  'buttonEnterActive': string;
  'buttonExit': string;
  'buttonExitActive': string;
  'grey': string;
  'image': string;
  'image_button': string;
  'info_container': string;
  'input': string;
  'red': string;
  'text': string;
  'text2': string;
  'title': string;
  'title2': string;
}
export const cssExports: CssExports;
export default cssExports;
