// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'blue_background': string;
  'blue_text': string;
  'button': string;
  'description': string;
  'gray_background': string;
  'main': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
