// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'input': string;
  'input_wrp': string;
  'input_wrp_text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
