// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'back': string;
  'block': string;
  'blue_background': string;
  'blue_text': string;
  'button': string;
  'description': string;
  'error': string;
  'errors': string;
  'gray_background': string;
  'input': string;
  'main': string;
  'menu': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
