// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'edit_blue': string;
  'edit_white': string;
  'logo': string;
  'logo_large': string;
  'menu_button': string;
  'menu_panel': string;
}
export const cssExports: CssExports;
export default cssExports;
