// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue_background': string;
  'blue_text': string;
  'edit_blue': string;
  'edit_white': string;
  'gray_background': string;
  'logo': string;
  'logo_large': string;
  'menu_button': string;
  'menu_panel': string;
}
export const cssExports: CssExports;
export default cssExports;
