// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block_title': string;
  'button': string;
  'image': string;
  'image_button': string;
}
export const cssExports: CssExports;
export default cssExports;
