// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block_title': string;
  'overlay': string;
  'popup': string;
  'red': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
