// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue_background': string;
  'description': string;
  'gray_background': string;
  'image': string;
  'image_default': string;
  'image_text': string;
  'info': string;
  'name': string;
}
export const cssExports: CssExports;
export default cssExports;
